### ISSUE TITLE
Chunks not needed

### ISSUE THREAD

**Issue by ghost** [jaspervdj/websockets-snap#28]
Hi Jasper,

I've been studying your websockets-snap  Snap.hs file and discovered that the paragraph:

```
data Chunk
    = Chunk ByteString
    | Eof
    | Error SomeException
    deriving (Show)

```

is not used.  Just thought you would like to know.  I'm studying your code so I can try to get server sent events to work.  Thank you for your contributions.
Best wishes,
Henry Laxen

**Comment by jaspervdj** [comment]
You are right, thanks!
